### ISSUE TITLE
error "Locomotive::Coal::UnauthorizedError" how should i do

### ISSUE THREAD

**Issue by surachet6** [locomotivecms/coal#18]
I'm newbie for locomotivecms. I have a question. I can't pull and deploy the site from engine which installed on my company server to wagon on my machine, the error is "Pulling...\Locomotive::Coal::UnauthorizedError", but i can pull and deploy to locomotivecms demo server as anytime I want, how should I do?

Sorry for my english.

**Comment by did** [comment]
hi @surachet6,

What's the version of the Locomotive instance running on your company server? What's the version of Wagon you're using?

**Comment by surachet6** [comment]
Sorry, forget the above error. It was because of my server was in private network not accessible from my local development machine. Does Locomotive support deployments through SSH tunnels?

**Comment by did** [comment]
I'd say yes, I don't see why it wouldn't
